### ISSUE TITLE
Add support for relative file path or obsidian links

### ISSUE THREAD

**Issue by Musickiller** [coddingtonbear/obsidian-csv-table#11]
Hello!

Please add support for relative file path or obsidian links!

It's really uncomfortable to write full path always!

**Comment by coddingtonbear** [comment]
Hey there, yeah, I'd be willing to help point somebody toward how to put something like that together.  In any case, maybe you could put together a PR adding that, or, if you don't know how to program, you could start a discussion from the "Discussions" tab above to see if you could convince somebody into helping you.  Good luck!
