### ISSUE TITLE
Support links inside table

### ISSUE THREAD

**Issue by NeighNeighNeigh** [coddingtonbear/obsidian-csv-table#2]
Hi there,

I've started using tables more heavily in Obsidian. I would love to use your plugin, but I use a lot of links inside my tables. Unfortunately these are not displayed as clickable links when obsidian-csv-table parses them. Any chance this could be included?

Thanks :)

**Comment by coddingtonbear** [comment]
Totally could be!  If you were to post a PR adding that, I'd definitely be willing to merge it.

**Comment by NeighNeighNeigh** [comment]
Ah sadly my skills are in animation, not plugin creation, so can only be helpful with feedback and ideas.

**Comment by coddingtonbear** [comment]
Don't sell yourself short, @NeighNeighNeigh -- it's never too late to learn a new skill.  As it stands, I'm not likely to find the time to work on such a feature personally in the foreseeable future, but I'd be glad to offer you help in your first steps toward learning how to add such a feature to a plugin like this one.  It's really not as difficult as it might look at first glance!

**Comment by NeighNeighNeigh** [comment]
Well, I would be happy to at least take a crack at it, but the most I've done is cobbling together javascript expressions in After Effects and hacking around some HTML and CSS to make Obsidian feel like it's mine. I am very very novice

**Comment by coddingtonbear** [comment]
I've thought it through and decided that feature requests are probably better started as discussions so as to keep the issues panel limited to actual, real problems. This is mostly for helping my sanity as, you might not have noticed, I have more than a few active projects on github that I'm the main or only maintainer for. If you're still interested in this, perhaps you could start a discussion there to see if you can find somebody to help put something like that together.  Cheers!

**Comment by holstuwe** [comment]
> Don't sell yourself short, @NeighNeighNeigh -- it's never too late to learn a new skill. As it stands, I'm not likely to find the time to work on such a feature personally in the foreseeable future, but I'd be glad to offer you help in your first steps toward learning how to add such a feature to a plugin like this one. It's really not as difficult as it might look at first glance!

I take this one as a motivational speech to learn HTML/CSS/Javascript. Thank you Sir!
