### ISSUE TITLE
Can't convert csv file into table when separator is semicolon

### ISSUE THREAD

**Issue by FlameHorizon** [coddingtonbear/obsidian-csv-table#29]
Hello,

I have this file which is delimiter is semicolon ";".

```csv
a;b;c
1;2;3
```

I'm using following code but without avail:

```csvtable
csvOptions:
- delimiter: ';'

source: random.csv
```

![image](https://github.com/coddingtonbear/obsidian-csv-table/assets/23423558/b22aa3c4-ab18-4376-aecc-2eba31bc8fbb)

I've tried also changing single quotes around semicolon into double quotes and over various things, but still, no progress.

It works well if you change the delimiter in the file itself to ",".

Could please point me to right direction how can I make it to working with semicolon? Thanks.

**Comment by ImN1** [comment]
@FlameHorizon
use this
```
csvOptions:
  delimiter: ";"
```

iden before option, it's sub dict format, not list.

**Comment by jerrygreen** [comment]
It would be cool if there were global options inside extension itself.
Don't quite like the idea messing with configs inside the actual notes.
