### ISSUE TITLE
Display truncated when lacking column 'title names'. meaning, empty cells in the first row

### ISSUE THREAD

**Issue by Hunanbean** [coddingtonbear/obsidian-csv-table#9]
for example, if this is the content of the csv file:

`this,is,,,,`
`a,test,rows and,columns stuff,1,4`
`asd,dfg,ghj,jkk,2,3`

it would truncate everything after the 'is' column, but it would pick up the last column.

Thank you

**Comment by coddingtonbear** [comment]
Unfortunately, supporting unnamed columns is probably impossible to support given how the library we're using for parsing CSV files works, and how this library was written to use it; so I'm going to close this as "Won't Fix".  Sorry, @Hunanbean!

**Comment by Hunanbean** [comment]
I appreciate the useful tool, regardless.

Thanks a bunch for it!
